dist: xenial
language: python
python:
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: 4oLUAb/fqlIAAxv+WnymJx3q7xwrsC8VTz/XiQEj0wWRkLt9q4tyC3zEUw3M+/FgYTuatwbOLX/eWkP7x/o3L19gm5c7PhvJ1lgFOj5bqT32u9Jw++POrC7ykKhmDkVElA4r5M5g5WgSfW2QZ9O0Ycj33UowJrMXi2UeBlCz72JRnA4o6zOTCbhdOqTSkGxrQhmIi5P3SFEgAhwT2mFeQjH2+XJOQxC4erFJQv299h81CyejooDKUGUDnUmFVlMmgGyyDXqYlo6bvzkmqwhffo3hLR6PfGs2q88kEryBozEZYG+7zrJ9AYiStL5n+VYeOxTkXKUiZyLDoRkl0j3Gr+KlFvyQU1mUT3dun143c161CkIpKNIL3f4DdXcjepB/um+tcsl04zlSiIgriMg7CH9fglXEOmL8VQxKvPebVRrLzuH88SS3IywUtZUR8jHnNrf+hDCSAGis80eQBBxlEkcZ0FdSQBmGZH2iEZHzTTLAXYbKdTGfiryZgF5Ym460KX4Xp9dqcgaGdI8yFHd8WsHKRNlx3g8XRe5w2upK4Rd63CtSjHSg6g0CfIcNSvHa1Q0I85oWs/Jvq0aM/5qqdHCpVnrHBMq6G79Zchzf9N1KZVooTbbQ42jRvhsmoWiH41SSEzX3O3rnPvRgWw/BGMlZ07A8uBs2f65sQMNRprs=
  on:
    repo: seanpue/graphtransliterator
    python: 3.7
    tags: true
