dist: xenial
language: python
python:
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: seanpue
  password:
    secure: NPVTDe564J9zVwEhVOAYDzBuHtl6mUZ2InavPv3z1APPtiGQGGhcx5TvQ4tapr0mOR1jL3RJpHDH+DHrxb+ayoebGSnYgYmm19WxFmKD5Cod6dQe67S5fq3gfAo8AkYaF+HfkVDzaRz8NF/TMkb/5eGYeBTITiolGV9bHtx+vPEemJyK9SvyRyEvG029l/ET8JmzH767r5YSdDg262SRHsJbHjyQ6GHsS6She/ju9mtSt1a91FhJUWXOFGJjLQOP8GNAopE8+0EeF12zul8Wg1qnssJCtebIdVztu4255kHEib+WUmZWYWNxZNQaGcrR5BXJsxEFUuMCHeKUNExPBTfKaAeXzvLgh/YVU3Zt7eLHBSg+ZPtqLXejjh10kWUpjz/T7WqaYwoFL/mRtGO6kENxqKx97+U7w442zEnVLs6go7UvnvXSvepMCRSSrNgK957Lg8litbhyXEG/St7ZUwBI8DIwl8Q6jJk4Z3upxNMTVoWhGwoZNgGTLTTMJSayo831fNl0IO1r0fZq0pHSLthp4kqv58dotTuvym51nDGSHjnZDgcZ+Tei5C+Xlr26OAJ1BIjZKkPrpkR2zeWoyWDLQucgXTsH94C4TtPnvWW1GD9N28Wm2BJS4n7lSXeMqf4MZhEfEeNwaIF63mlWYZS0LltyCH4UM3C8JG3zhdE=
  on:
    repo: seanpue/graphtransliterator
    python: 3.6
