dist: xenial
language: python
python:
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: seanpue
  password:
    secure: wE0OphJ6LvNtiVAvBJ9TMJwz9GNcudQ1ejVxPj67uBxTOM7zu5+QnESZbyCzYl6PHvenS00Ra0o2ZvmraP+fStOYb6ar6bHd4grM3XscxBBvE+4UqCPacPGPkkTrDU+HWFJTsH/7S158oZXOzkG2rFoHeMSIBRgPpwFMP+c++ptUpN7H17SYHqtQZCOAnksXdDwvgKPzOqkvYSvFpYKWsaGTJHGkSgiR/94he5jv+M4/kV0bzMrYUg1IsgkuLGSvw5C9m9tbODlV4YmjXKgshunHE6qzdsdjY6yhnQOjwWx75vdYM0FIV3yCZGS/VOtgTjDzWoJ0XzgSA3qlFsSdS4pvIJa/8Sz0LjtJ2WGBuRlEd4v71jTtTSU8+EX3E5s8iMXQ8DVx8vS8A/dEQb7/LvOWbGeTGg7PoV6KvZXOcWoS/VuFa5CN6UasJiYdOMg28i46WD2TpKHa5d4VnChMAFjYztylmK0Sa45Ut76joPvLAzGaWvBNQkt66DtVZKZNe9W/CTnYmm+SCqZ6356NvVF+pB8hU9gf/l9TT/dSyOY2V+9DZvp5+qTPbKEImNMNTT2I1NLMhwQM61n2mGwdKF+l5Rlm3j7qtvoc7ylCllvzHU117GHiJ83mCfRhRjLUAaBJWqXzMet3qWipjqMVzoQWN9Auvff1ZOfILc3TO7M=
  on:
    repo: seanpue/graphtransliterator
    python: 3.6
