dist: xenial
language: python
python:
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: atulVDMRLEUHKGrD3Mtr8j+o3wr3SUed1OwA17ubAIWiAPB7JnRO/klDxvH/Ss1x4tW0jxrSt4YWQ3MuMhd8qWif3Szdi1Ta9oW969Jy91NX5xLIy8NOR6joPVWSI+V9sGulmrTPdGlcty7dbe05MYNxjhJCsD/8kulGZ0spmxAfPRiAoNu9YlB2mE+ySCAZwf3oNJGgAEXedWD3T3eO/1WSd7JSxLHamt4xKgAR2OiNVVhHGT+OcXWzab+VRsp95MamgBYAgzNYehJNvN0jeGFnPXV3ZFYe01eCyAUREDfaQeM4UScf/4tnY3AAmpVhoF/4FioU5bBGHSE0JPyXT9SkpzRLsT6XyZv9+pu/7bxkFkssaR6PbpVUQVlOW+AtcMCBBaNOQWKaFzu3AIOTTER19AgT014CtCR90JwYh8HcRvVJwDWli5UwRsrBwU48+lYwhUbjJcxSth+//0Sc7FXfeZ4ZJoU+wcKUDlgHGXklIM6bo/U8Sgc2z7uAZaAZzOTRNwhwcmmptowbSKim7/NhL9AN0uyNyDr+UzAItIStMLKsh5/TIRsQi02FgAcEGkPN7ZmGW2KPGL7rn8CwQDd5ZnGT3wjsbJkls3wfoByb3GrEqmLpnwnZkMOEB9TIjzhz6WHYGidVa/Wowy2tul1JPKeADY0x4OIsu7jkR/g=
  on:
    repo: seanpue/graphtransliterator
    python: 3.7
    tags: true
